-- 1. Таблиця їжі
CREATE TABLE IF NOT EXISTS foods (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    image_url TEXT,
    food_type TEXT,
    meal_type TEXT,
    tags TEXT[] DEFAULT '{}'::TEXT[],
    source TEXT,
    external_id TEXT,
    ingredients TEXT,
    instructions TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE foods ADD COLUMN IF NOT EXISTS source TEXT;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS external_id TEXT;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS ingredients TEXT;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS instructions TEXT;
ALTER TABLE foods ADD COLUMN IF NOT EXISTS created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL;

-- 2. Таблиця ігрових кімнат
CREATE TABLE IF NOT EXISTS rooms (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_1_name TEXT NOT NULL,
    user_2_name TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Таблиця свайпів
CREATE TABLE IF NOT EXISTS swipes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_id UUID REFERENCES rooms(id) ON DELETE CASCADE NOT NULL,
    user_name TEXT NOT NULL,
    food_id UUID REFERENCES foods(id) ON DELETE CASCADE NOT NULL,
    action TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_swipes_room_user ON swipes(room_id, user_name);
CREATE INDEX IF NOT EXISTS idx_foods_filtering ON foods(food_type, meal_type);
CREATE UNIQUE INDEX IF NOT EXISTS idx_foods_source_external_id ON foods(source, external_id) WHERE source IS NOT NULL AND external_id IS NOT NULL;

-- 4. Public MVP access for the browser anon client.
-- The app does not use Supabase Auth yet, so RLS needs explicit anon policies.
ALTER TABLE foods ENABLE ROW LEVEL SECURITY;
ALTER TABLE rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE swipes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "foods_select_anon" ON foods;
CREATE POLICY "foods_select_anon"
ON foods FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "foods_insert_anon" ON foods;
CREATE POLICY "foods_insert_anon"
ON foods FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "rooms_select_anon" ON rooms;
CREATE POLICY "rooms_select_anon"
ON rooms FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "rooms_insert_anon" ON rooms;
CREATE POLICY "rooms_insert_anon"
ON rooms FOR INSERT
TO anon
WITH CHECK (true);

DROP POLICY IF EXISTS "rooms_update_second_player_anon" ON rooms;
CREATE POLICY "rooms_update_second_player_anon"
ON rooms FOR UPDATE
TO anon
USING (true)
WITH CHECK (true);

DROP POLICY IF EXISTS "swipes_select_anon" ON swipes;
CREATE POLICY "swipes_select_anon"
ON swipes FOR SELECT
TO anon
USING (true);

DROP POLICY IF EXISTS "swipes_insert_anon" ON swipes;
CREATE POLICY "swipes_insert_anon"
ON swipes FOR INSERT
TO anon
WITH CHECK (action IN ('like', 'dislike'));

DROP POLICY IF EXISTS "swipes_delete_anon" ON swipes;
CREATE POLICY "swipes_delete_anon"
ON swipes FOR DELETE
TO anon
USING (true);
